createGetter, invertObj, trimSymbols and uniq functions
js-tasks-ru/js-20220111_user0308 pull request #3
Opened 2022-01-21 13:46 UTC by acromatica

2022-01-21 13:47 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-21 15:49 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return path.split('.').reduce((previousValue, currentValue) => previousValue?.[currentValue], obj);
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-01-21 15:49 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if(obj) return Object.fromEntries(Object.entries(obj).map(([a, b]) => [b, a]));
старайтесь такие операции разбивать на несколько строк кода, 
человеку который не знаком с данной задачей, будет очен трубно понять
что тут происходит

2022-01-21 15:49 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  return string.split('').reduce((prevString, currentChar) => {
good 👍

2022-01-21 15:50 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr));
подумайте какие есть преимущества у `Array.from` по сравнению с спред-синтаксисом:
```
return [...new Set(arr)]
```

2022-01-21 15:50 UTC, dosandk requested changes
`createGetter` задачу следует поправить

2022-01-21 16:49 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-21 17:02 UTC, acromatica commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr));
Array.from работает как с псевдомассивами, так и с итерируемыми объектами, a спред-синтаксис только с итерируемыми объектами? Конкретно в этом случае разницы никакой, Array.from разве что читаемей, наверное.

2022-01-24 23:51 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return Array.from(new Set(arr));
разницы никакой, кроме того что в `Array.from` мы можем передать дополнительный аргумент - `map` функцию которая сработает на каждом элементе

2022-01-24 23:52 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  const pathArr = path.split('.');
👍 лайк за использование замыкания

2022-01-24 23:53 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return pathArr.reduce((previousValue, currentValue) => previousValue?.[currentValue], obj);
у `reduce` есть небольшой недостаток, мы не можем оборвать итерацию, если уже добрались до самого вложенного элемента объекта

2022-01-24 23:53 UTC, dosandk approved these changes
good 👍

2022-01-24 23:53 UTC, merged